# config.yaml
# This configuration is specific to the original script with the "Purify" block disabled.

paths:
  # These paths are active and used by the script.
  raw_data_path: "chunk3.bin"
  channel_map_path: "channel_positions.npy"
  output_dir: "output"

recording:
  # These recording parameters are active and used by the script.
  n_channels: 512
  sampling_rate: 20000
  dtype: 'int16'

testing:
  # These testing parameters are active and used by the script.
  enabled: true
  duration_sec: 30
  max_units: 5

pipeline:
  # These pipeline parameters are active and used by the script.
  max_units_to_find: 5000
  window_pre_samples: -40
  window_post_samples: 80
  refractory_samples: 10

  # NOTE: This parameter is IGNORED. The script has a hardcoded p2p_threshold of 30.
  #p2p_threshold_subtraction: 30
  
  # NOTE: The following parameters are from the corrected script and have NO EFFECT on this version.
  # min_spikes_for_final_unit: 100
  # similarity_threshold_for_merge: 0.95

preprocessing:
  # This parameter is active and used by the script.
  segment_len: 20000

  # NOTE: The following parameters are IGNORED. The script uses hardcoded values.
  # diff_thresh is hardcoded as 10.
  # trim_fraction is hardcoded as 0.15.
  # diff_thresh: 10
  # trim_fraction: 0.15